//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartina2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finition()
        {
            this.Cadre = new HashSet<Cadre>();
            this.Format1 = new HashSet<Format>();
        }
    
        public int id { get; set; }
        public string Label { get; set; }
        public int Prix { get; set; }
    
        public virtual Finition Finition1 { get; set; }
        public virtual Finition Finition2 { get; set; }
        public virtual Format Format { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cadre> Cadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Format> Format1 { get; set; }
    }
}
