//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartinaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCommande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailCommande()
        {
            this.Photo1 = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public int NbPhotos { get; set; }
        public int IDCommande { get; set; }
        public int PrixPhoto { get; set; }
        public int IDPhoto { get; set; }
        public int IDFormat { get; set; }
        public int IDFinition { get; set; }
        public int IDCadre { get; set; }
    
        public virtual Cadre Cadre { get; set; }
        public virtual Commande Commande { get; set; }
        public virtual Format Format { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo1 { get; set; }
    }
}
